
name: ASAM QC OpenDRIVE/OpenSCENARIO XML

on:
  pull_request:
    branches:
      - '**'

jobs:
  build_qc_framework:
    name: Build ASAM QC Framework
    runs-on: ubuntu-latest

    steps:
      - name: Cache QC Framework
        id: cache-qc-framework
        uses: actions/cache@v4
        with:
          path: qc-build
          key: ${{ runner.os }}-qc-build

      - name: Install dependencies
        run: sudo apt install -y g++ g++-10 make build-essential cmake libgtest-dev qtbase5-dev libqt5xmlpatterns5-dev libxerces-c-dev pkg-config python3-venv git

      - name: Get QC Framework
        if: steps.cache-qc-framework.outputs.cache-hit != 'true'
        run: git clone https://github.com/asam-ev/qc-framework.git

      - name: Copy Commit ID to Cache
        if: steps.cache-qc-framework.outputs.cache-hit != 'true'
        working-directory: qc-framework
        run: git rev-parse --short HEAD > commit-id.txt

      - name: Build QC Framework
        if: steps.cache-qc-framework.outputs.cache-hit != 'true'
        working-directory: qc-framework
        run: |
          mkdir build
          cmake -G "Unix Makefiles" -B./build -S . \
            -DCMAKE_INSTALL_PREFIX="../qc-build" \
            -DENABLE_FUNCTIONAL_TESTS=ON  -DXERCES_ROOT="/usr" \
            -DQt5_DIR="/usr/lib/x86_64-linux-gnu/cmake/Qt5/" \
            -DQt5XmlPatterns_DIR="/usr/lib/x86_64-linux-gnu/cmake/Qt5XmlPatterns/"
          cmake --build ./build --target install --config Release -j4
          cmake --install ./build

      - name: Commit ID
        working-directory: qc-framework
        run: |
          echo "Commit ID: "
          echo $(cat commit-id.txt)

  asam_qc_opendrive_openscenarioxml:
    runs-on: ubuntu-latest
    needs: build_qc_framework
    env:
      CI_COMMIT_REF_NAME: ${{ github.head_ref }}
      CI_MERGE_REQUEST_DIFF_BASE_SHA: ${{ github.event.pull_request.base.sha }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed for diff
      - name: Cache QC Framework
        id: cache-qc-framework
        uses: actions/cache@v4
        with:
          path: qc-build
          key: ${{ runner.os }}-qc-build
      - name: Find changed files
        id: changed-files
        run: |
          CHANGED_FILES=$(git diff --name-status $CI_MERGE_REQUEST_DIFF_BASE_SHA -- '*.xodr' '*.xosc' | awk '$1 != "D" {print $2}')
          echo "changed_files=$CHANGED_FILES" >> $GITHUB_OUTPUT
      - name: Run QC tests
        if: steps.changed-files.outputs.changed_files != ''
        run: |
          for FILE in ${{ steps.changed-files.outputs.changed_files }}; do
            echo "Running tests for $FILE"
            docker run \
              -e INPUT_FILENAME=$FILE \
              -v $(pwd):/input_directory \
              -v $(pwd):/out \
              -e USER_ID=$(id -u) \
              -e GROUP_ID=$(id -g) \
              --rm --name demo_pipeline ghcr.io/asam-ev/qc-framework:demo-pipeline-latest
            ls -l
            cd qc-build/bin
            ls -l
            .GithubCIReport qc-result-$FILE/Result.xqar
          done
          touch junit_report.xml

      - name: Upload Report for Debugging
        uses: actions/upload-artifact@v4
        with:
          name: Result.xqar
          path: qc-result-xodr/german_highway_short.xodr/Result.xqar

      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: junit_report.xml
