
name: ASAM QC OpenDRIVE/OpenSCENARIO XML

on:
  pull_request:
    branches:
      - '**'

jobs:
  asam_qc_opendrive_openscenarioxml:
    runs-on: ubuntu-latest
    env:
      CI_COMMIT_REF_NAME: ${{ github.head_ref }}
      CI_MERGE_REQUEST_DIFF_BASE_SHA: ${{ github.event.pull_request.base.sha }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed for diff
      - name: Wait for Docker daemon
        run: |
          echo "Waiting for docker daemon to be fully started"
          until docker info; do sleep 1; done
      - name: Find changed files
        id: changed-files
        run: |
          CHANGED_FILES=$(git diff --name-status $CI_MERGE_REQUEST_DIFF_BASE_SHA -- '*.xodr' '*.xosc' | awk '$1 != "D" {print $2}')
          echo "changed_files=$CHANGED_FILES" >> $GITHUB_OUTPUT
      - name: Run QC tests
        if: steps.changed-files.outputs.changed_files != ''
        run: |
          touch junit_report.xml
          for FILE in ${{ steps.changed-files.outputs.changed_files }}; do
            echo "Running tests for $FILE"
            docker run \
              -e INPUT_FILENAME=$FILE \
              -v $(pwd):/input_directory \
              -v $(pwd):/out \
              -e USER_ID=$(id -u) \
              -e GROUP_ID=$(id -g) \
              --rm --name demo_pipeline ghcr.io/asam-ev/qc-framework:demo-pipeline-latest
          done

      - name: Upload Report for Debugging
        uses: actions/upload-artifact@v4
        with:
          name: Result.xqar
          path: qc-result-xodr/german_highway_short.xodr/Result.xqar

      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: junit_report.xml
